apiVersion: v1
kind: Namespace
metadata:
  name: bigbang
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: environment-repo
  namespace: bigbang
spec:
  interval: 1m
  url: ssh://git@github.com/shyangt/bootstrap.git
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: environment
  namespace: bigbang
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./dev
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  kind: Shared
  resourceGroup: BB8
#  encrypted: 'true' #requires kubernetes nodes have IAM rights, commented out for lab env
#  azure_kv: 'https://sops-41c9aebbb1e54d57.vault.azure.net/keys/sops-bb8-key/1dd2a9f620d8422598b8088d5e8fb2bf'
reclaimPolicy: Delete #recommended for lab/dev env
allowVolumeExpansion: true

