apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:oiimyd0lwLcPZUWoeyg/aYJ1khqqNIDfwjHg7s589J3Vnp9h254qiY+p8ZRt/K1bL2OKRzobr2kF284RCRp86NOLL+bn8EjEdDTYGb2r4gVaR0TuCJEh3F4PIWY/pYS0,iv:EPpVcg1uQZAu9Xcd0s719PbQpe4q1If8iKRSKTi2y7g=,tag:13lCxtutwkeHe+WAvol60w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-26T14:56:29Z'
    mac: ENC[AES256_GCM,data:XiFXcPyMdh2rMFwnOXCux9KV7x0PbaStkthI4Smo6r/o284pGxEoAo0xJ6O8vJU62NajHH6CWIPx7NHJQG+kfPOz8kRvf0tJyAsj6MDaM+NJkggE9cqYjo4htXjk2IMjW9DKmaiNo20wSYHFmAGWxzuc7MEA2HJWSUKHILSS3Mg=,iv:NKJCR67oqEYICtqG4MIi/uD38yCknihHlKBPckQzmA0=,tag:0aexLrVOlmpAXGKFuqm47g==,type:str]
    pgp:
    -   created_at: '2021-05-26T14:49:52Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9mtdQaUm9iYAQ/9H89wwyoDDa+3etKrORNkMbtu4eSP7WBkI/utRxYr1dz2
            y0a4vMr0LZhStHjA3CLVw8KWJIFsUq8zOq/H4OyYTQHvS7p+6N2mRD0FSN0LmQHv
            ycc7PU5g/v5AwjGmQG2IBEPy7mfiRtlNX75MU2rXvXKH6H19lwnuj6JH5ORr3v15
            3Z71fBwDHCYj0bcLbEaUHhNxhdKa1dD1YaLdWUaQkd78ROp+2ghWHr0tCLACXWYh
            MezCN5pN1xyZ5b4nKi+6Gn5i5J4WXtT/KBvFq8OIUT2C7cZsGvZRuTiffoXFtGy4
            Aa6RNvyPDQ9s6AHt9oRqjlOVu2I52eJF/YsaKevBW2iTtTFfaBJOmkDmNm3SWPY0
            MfHvAwFdh4gIsjfm8SU30VoGLBHZIMpwqHlwnDVptpXNpWwnuLU8cfKo5Tc9ZmxQ
            iEg/F9qGa0CGnUBYQFPRyZInlb78AdZ/RhY6Yj5g6FG/FX4HC5rxxAP3XG24EXx2
            JAoTQ4y7HqLt2uYcF3iPfCYQLd7zsb3tm0ksp2/hadJXhHE3RnfJHGDbPk97/iu8
            G43EmxtDuj+beNQNwng7yFqd6Ly8AqLIYamoRRmfU1AOXRXRu28KJbfSJzURhB27
            LNOZeU+rR4uBJy2FOk09HU8OriqdJiOmb1pH6ACEDJLHEFSKGXLHETnWFXWtMhHS
            XAG6Y05qOqDLfq+LFLE6B9NRueKhobVNB3XB+shfKBr42sy7pSw59kb1m0Oex8QO
            WY77ycn/fG6LNfu85llVzcXnNOK+47Uxo8eqJQZxYp4Elw0os/bqvW72GZIq
            =Ks9t
            -----END PGP MESSAGE-----
        fp: A37D05C3C390CFDC81D3C1923887C217D9B04596
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
